#' @author Nikolas Barkas
#' @importFrom utils read.table
#' @importFrom Matrix readMM
NULL

#' @title  Read 10x matrix
#' @description This function reads a matrix generated by the 10x processing pipeline
#' from the specified directory and returns it. It aborts if one of the required
#' files in the specified directory do not exist.
#'
#' @param path location of 10x output
#'
#' @return read matrix
#'
#' @export read10xMatrix
read10xMatrix <- function(path) {
  matrixFile <- paste(path, 'matrix.mtx', sep='/');
  genesFile <- paste(path, 'genes.tsv', sep='/');
  barcodesFile <- paste(path, 'barcodes.tsv', sep='/');

  if (!file.exists(matrixFile)) { stop('Matrix file does not exist');  }
  if (!file.exists(genesFile)) { stop('Genes file does not exist'); }
  if (!file.exists(barcodesFile)) { stop('Barcodes file does not exist'); }

  x <- as.matrix(readMM(matrixFile));
  genes <- read.table(genesFile)
  rownames(x) <- genes[,2];
  barcodes <- read.table(barcodesFile);
  colnames(x) <- barcodes[,1]
  storage.mode(x) <- 'integer'
  invisible(x);
}
